package com.example.wharfstreetstudiostask1.data.local

/**
 * Author: Vidurraje Deshmukh
 * Date: 2025-09-26
 */
import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a post entity in the local Room database.
 *
 * Each post contains a title, description, author, and counters for likes and dislikes.
 * The [id] is autogenerated and serves as the primary key.
 *
 * @property id Unique identifier for the post (autogenerated).
 * @property title The title of the post.
 * @property description The content or body of the post.
 * @property author The name of the person who created the post.
 * @property likes The number of likes this post has received.
 * @property dislikes The number of dislikes this post has received.
 */
@Entity(tableName = "posts")
data class PostEntity(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val title: String,
    val description: String,
    val author: String,
    var likes: Int = 0,
    val dislikes: Int = 0
)


